const {test}=require('node:test');
const assert=require('node:assert/strict');
const core=require('../apps-script/Core.js');
const now=Date.parse('2026-09-20T12:00:00-03:00');
function config(){return {eventos:['ept','eja'].map(id=>({id,nome:id.toUpperCase(),data:'2026-10-07',status:'ABERTO',abertura:'2026-09-01T00:00:00-03:00',encerramento:'2026-10-01T18:00:00-03:00',limite:250,limiteMunicipio:1})),funcoes:['ept','eja'].flatMap(eventoId=>[{eventoId,id:'inst',nome:'Instituição',tipo:'INSTITUCIONAL',limite:250,ativa:true},{eventoId,id:'secretario',nome:'Secretário(a)',tipo:'MUNICIPAL',limite:10,grupo:'municipais',ativa:true},{eventoId,id:'tecnico',nome:'Técnico',tipo:'MUNICIPAL',limite:10,grupo:'municipais',ativa:true},{eventoId,id:'nte-01-diretor',nome:'Diretor(a)',tipo:'NTE',nte:'NTE 01',limite:1,ativa:true}]),municipios:[{nome:'Salvador',nte:'NTE 26'}]};}
function data(extra={}){return {eventoId:'ept',nome:'Pessoa de Teste',cpf:'529.982.247-25',telefone:'71999999999',email:'teste@example.invalid',funcaoId:'inst',municipio:'',requestId:'request-00000000001',...extra};}
function code(fn,expected){assert.throws(fn,e=>e.code===expected);}
test('CPF com dígitos corretos e formatos diferentes; rejeita repetidos e checksum errado',()=>{assert.equal(core.validCPF('529.982.247-25'),true);assert.equal(core.validCPF('52998224725'),true);assert.equal(core.validCPF('11111111111'),false);assert.equal(core.validCPF('52998224726'),false);});
test('mesmo CPF em dois eventos; duplicidade dentro do evento é bloqueada',()=>{const r=core.prepare(data(),config(),[],now).record;assert.ok(core.prepare(data({eventoId:'eja',requestId:'request-00000000002'}),config(),[r],now).record);code(()=>core.prepare(data({requestId:'request-00000000002'}),config(),[r],now),'DUPLICATE_CPF');});
test('limite total 250 sem somar inscrições do outro evento',()=>{const rows=Array.from({length:250},()=>({eventoId:'ept',status:'CONFIRMADA',cpf:'',grupoVagas:'inst'}));code(()=>core.prepare(data(),config(),rows,now),'SOLD_OUT');assert.ok(core.prepare(data({eventoId:'eja'}),config(),rows,now).record);});
test('zero e configuração ausente não liberam vagas',()=>{let c=config();c.funcoes[0].limite=0;code(()=>core.prepare(data(),c,[],now),'ROLE_SOLD_OUT');c.funcoes[0].limite=NaN;code(()=>core.prepare(data(),c,[],now),'CONFIG_ERROR');});
test('grupo municipal compartilha cota e limita município',()=>{const c=config();const r=core.prepare(data({funcaoId:'secretario',municipio:'Salvador'}),c,[],now).record;code(()=>core.prepare(data({cpf:'11144477735',requestId:'request-00000000002',funcaoId:'tecnico',municipio:'Salvador'}),c,[r],now),'MUNICIPALITY_SOLD_OUT');const out=core.publicEvent(c.eventos[0],c.funcoes,[r],now);assert.equal(out.funcoes.find(f=>f.id==='tecnico').disponiveis,9);assert.deepEqual(out.municipiosLotados,['Salvador']);});
test('função por NTE tem cota própria',()=>{const r=core.prepare(data({funcaoId:'nte-01-diretor'}),config(),[],now).record;assert.equal(r.nte,'NTE 01');code(()=>core.prepare(data({cpf:'11144477735',requestId:'request-00000000002',funcaoId:'nte-01-diretor'}),config(),[r],now),'ROLE_SOLD_OUT');});
test('evento, função, município e CPF inválidos rejeitados no servidor',()=>{code(()=>core.prepare(data({eventoId:'outro'}),config(),[],now),'INVALID_EVENT');code(()=>core.prepare(data({funcaoId:'inexistente'}),config(),[],now),'INVALID_ROLE');code(()=>core.prepare(data({funcaoId:'tecnico',municipio:'Inventado'}),config(),[],now),'INVALID_MUNICIPALITY');code(()=>core.prepare(data({cpf:'00000000000'}),config(),[],now),'INVALID_INPUT');});
test('prazos e rascunho impedem envio',()=>{const c=config();code(()=>core.prepare(data(),c,[],Date.parse(c.eventos[0].encerramento)),'EVENT_CLOSED');code(()=>core.prepare(data(),c,[],0),'EVENT_CLOSED');c.eventos[0].status='RASCUNHO';code(()=>core.prepare(data(),c,[],now),'EVENT_CLOSED');});
test('reenvio retorna inscrição existente mesmo após encerramento; alteração conflita',()=>{const r={...core.prepare(data(),config(),[],now).record,id:'protocolo'};assert.equal(core.prepare(data(),config(),[r],now+1e12).existing.id,'protocolo');code(()=>core.prepare(data({nome:'Outra Pessoa'}),config(),[r],now),'REQUEST_CONFLICT');});
test('disponibilidade pública não expõe dados pessoais',()=>{const r=core.prepare(data(),config(),[],now).record;const out=JSON.stringify(core.publicEvent(config().eventos[0],config().funcoes,[r],now));assert.ok(!out.includes(r.cpf));assert.ok(!out.includes(r.email));assert.ok(!out.includes(r.nome));});
test('cotas inconsistentes no mesmo grupo fecham evento',()=>{const c=config();c.funcoes.find(f=>f.id==='tecnico').limite=7;assert.equal(core.publicEvent(c.eventos[0],c.funcoes,[],now).estado,'FECHADO');});
test('texto parecido com fórmula permanece entrada textual; escrita é responsabilidade da camada Sheets',()=>{assert.equal(core.prepare(data({nome:'=HYPERLINK("x")'}),config(),[],now).record.nome,'=HYPERLINK("x")');});
